language: java
jdk:
  - oraclejdk8

# Don't let Travis CI execute './gradlew assemble' by default
install:
# Display Gradle, Groovy, JVM and other versions
- ./gradlew -version

script: ./gradlew clean test
