server:
  port: 8443
  ssl.key-store: security/keystore.p12
  ssl.key-store-password: Krumpli1
  ssl.keyStoreType: PKCS12
  ssl.keyAlias: tomcat

spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: dbuser
    password: dbpass
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2