spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: dbuser
    password: dbpass
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2


security:
  oauth2:
    client:
      clientId: 1857573394496421
      clientSecret: d335b4de2cfe256679d86cee4e7865da
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me